#!/bin/bash
cd /home/esmalif/cooperation/CVS/branch/0.9/0.9_code_cleaning

#rm -r /media/partage-dev/tmp/*

#sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/kubuntu-8.10-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/7a1 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-kubuntu-8.10-client-0.5.2.iso --ostype Client
 
#sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/kubuntu-8.04.1-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a2 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-kubuntu-8.04.1-client-0.5.2.iso --disautologin --ostype Client

#sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/ubuntu-8.04.1-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a3 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-ubuntu-8.04.1-client-0.5.2.iso --disautologin --ostype Client


#udo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/xubuntu-8.04.1-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a4 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-xubuntu-8.04.1-client-0.5.2.iso --disautologin --ostype Client


#sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/ubuntu-8.10-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a5 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-ubuntu-8.10-client-0.5.2.iso --disautologin --ostype Client

#sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/xubuntu-8.10-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a6 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-xubuntu-8.10-client-0.5.2.iso --disautologin --ostype Client

#sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/kubuntu-8.10-desktop-i386.iso --modulesfile templates/client_kubuntu_without_codec --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a7 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-kubuntu-8.10-client-0.5.2.iso --disautologin --ostype Client


#sudo ./cooperation-iws.py -c --createdirectories --modulesfile templates/empty --debmirror http://localhost:81/deb/mirror/ftp.fr.debian.org/debian/ --debmirrornonfree http://localhost:81/deb/mirror/mirror.home-dn.net/debian-multimedia/ --debmirrorsecurity ftp://security.debian.org/debian-security/ --directory /media/partage-dev/tmp/9a8 --host ciws-client  --outputisoname ciws-webconverger-eu-0.5.2.iso --keyblang fr --debianlive --webconverger --webappmirror http://localhost:81/depot --ostype Client

#sudo ./cooperation-iws.py -c --createdirectories --modulesfile templates/empty --debmirror http://localhost:81/deb/mirror/ftp.fr.debian.org/debian/ --debmirrornonfree http://localhost:81/deb/mirror/mirror.home-dn.net/debian-multimedia/ --debmirrorsecurity ftp://security.debian.org/debian-security/ --directory /media/partage-dev/tmp/10a9 --host ciws-client  --outputisoname ciws-webconverger-asia-0.5.2.iso --keyblang fr --debianlive --webconverger --webappmirror http://localhost:81/depot --ostype Client --webconvergerlocale webconverger-asia

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/edubuntu_8.10.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc81 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-edubuntu-8.10-0.7.0.iso --isotype edubuntu_8.10 --ostype Client --silent

##./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/eeebuntu-2.0-nbr.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc82 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-eeebuntu-nbr-2.0-0.7.0.iso --isotype eeebuntu_8.10 --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/eeebuntu-2.0-standard.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc810 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-eeebuntu-standard-2.0-0.7.0.iso --isotype eeebuntu_8.10 --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Maryan_Linux_RC.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc811 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-maryan-0.7.0.iso --isotype maryan_8.04.1 --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/nubuntu-8.12-beta.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/10zc812 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-nubuntu-8.12-0.7.0.iso --isotype nubuntu_8.10 --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/opengeu-8.04.1-desktop-i386.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc813 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-opengeu-8.04.1-0.7.0.iso --isotype opengeu_8.04.1 --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/ozos-0.9-livecd-i386.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/10zc814 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-ozos-0.9-0.7.0.iso --isotype ozos-0.9 --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Poseidon.3.1_32bits.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc816 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-poseidon-0.7.0.iso --isotype poseidon-3.1 --ostype Client --silent


#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/ubuntu_8.10_netbook_remix.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc817 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-netbook-remix-8.10-0.7.0.iso --isotype netbook-remix_8.10 --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/kubuntu-8.10-desktop-i386.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc818 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-kubuntu-8.10-0.7.0.iso --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/ubuntu-8.10-desktop-i386.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc819 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-ubuntu-8.10-0.7.0.iso --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/ubuntu_studio_8.10.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc820 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-gw-intranet-0.7.1.iso --isotype studio_8.10 --ostype Client --silent

#./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/eeebuntu-2.0-base.iso --modulesfile templates/client_gen --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/10zc82 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-eeebuntu-nbr-2.0-0.7.0.iso --isotype eeebuntu_8.10 --ostype Client --silent

./cooperation-iws.py -c --createdirectories --isofile /home/esmalif/cooperation/ISO/xubuntu-8.10-desktop-i386.iso --modulesfile templates/dev2 --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/a3 --host client --password cooperation --username ciwsadmin --artwork ciwsGnome --outputisoname cooperation-iws-ubuntu-8.10-0.7.0.iso --ostype Client



