#!/bin/bash
cd /media/cooperation-core/cooperation/CVS/branch/Pro/ciws_fully_auto


sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/kubuntu-8.10-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a1 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-kubuntu-8.10-client-0.5.2.iso --disautologin --ostype Client
 
sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/kubuntu-8.04.1-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a2 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-kubuntu-8.04.1-client-0.5.2.iso --disautologin --ostype Client

sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/ubuntu-8.04.1-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a3 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-ubuntu-8.04.1-client-0.5.2.iso --disautologin --ostype Client


sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/xubuntu-8.04.1-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a4 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-xubuntu-8.04.1-client-0.5.2.iso --disautologin --ostype Client


sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/ubuntu-8.10-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a5 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-ubuntu-8.10-client-0.5.2.iso --disautologin --ostype Client

sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/xubuntu-8.10-desktop-i386.iso --modulesfile templates/client_kubuntu --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a6 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-xubuntu-8.10-client-0.5.2.iso --disautologin --ostype Client

sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/kubuntu-8.10-desktop-i386.iso --modulesfile templates/client_kubuntu_without_codec --webappmirror http://localhost:81/depot --debmirror http://localhost:81/deb/mirror/ftp.proxad.net/mirrors/ftp.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:81/deb/mirror/packages.medibuntu.org/ --directory /media/partage-dev/tmp/6a7 --host ciws-client --password cooperation --username ciwsadmin --silent --outputisoname ciws-kubuntu-8.10-client-0.5.2.iso --disautologin --ostype Client


sudo ./cooperation-iws.py -c --createdirectories --modulesfile templates/empty --debmirror http://localhost:81/deb/mirror/ftp.fr.debian.org/debian/ --debmirrornonfree http://localhost:81/deb/mirror/mirror.home-dn.net/debian-multimedia/ --debmirrorsecurity http://localhost:81/deb/mirror/security.debian.org/ --directory /media/partage-dev/tmp/6a8 --host ciws-client  --outputisoname ciws-webconverger-eu-0.5.2.iso --keyblang fr --debianlive --webconverger --webappmirror http://localhost:81/depot --ostype Client

sudo ./cooperation-iws.py -c --createdirectories --modulesfile templates/empty --debmirror http://localhost:81/deb/mirror/ftp.fr.debian.org/debian/ --debmirrornonfree http://localhost:81/deb/mirror/mirror.home-dn.net/debian-multimedia/ --debmirrorsecurity http://localhost:81/deb/mirror/security.debian.org/ --directory /media/partage-dev/tmp/6a9 --host ciws-client  --outputisoname ciws-webconverger-eu-0.5.2.iso --keyblang fr --debianlive --webconverger --webappmirror http://localhost:81/depot --ostype Client --webconvergerlocale webconverger-asia

