#!/bin/bash
cd /home/esmalif/cooperation/CVS/branch/0.9/0.9_code_cleaning

rm -r /media/partage-dev/tmp/*

sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/ubuntu-8.04.1-desktop-i386.iso --modulesfile templates/upgrade_hardy --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --directory /media/partage-dev/tmp/j3 --outputisoname ubuntu-8.04.1-update-090310.iso --ostype Client --silent

sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/ubuntu-8.10-desktop-i386.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --directory /media/partage-dev/tmp/j5 --outputisoname cooperation-iws-ubuntu-8.10-update-090310.iso --ostype Client --silent

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/edubuntu_8.10.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc81 --host client --outputisoname cooperation-iws-edubuntu-8.10-update-090310.iso --isotype edubuntu_8.10 --ostype Client --silent

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/eeebuntu-2.0-nbr.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc82 --outputisoname cooperation-iws-eeebuntu-nbr-2.0-update-090310.iso --isotype eeebuntu_8.10 --ostype Client --silent

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/eeebuntu-2.0-standard.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc810 --outputisoname cooperation-iws-eeebuntu-standard-2.0-update-090310.iso --isotype eeebuntu_8.10 --ostype Client --silent

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/Maryan_Linux_RC.iso --modulesfile templates/upgrade_hardy --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc811 --outputisoname cooperation-iws-maryan-update-090310.iso --isotype maryan_8.04.1 --ostype Client --silent

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/nubuntu-8.12-beta.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/10zc812 --outputisoname cooperation-iws-nubuntu-8.12-update-090310.iso --isotype nubuntu_8.10 --ostype Client --silent

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/opengeu-8.04.1-desktop-i386.iso --modulesfile templates/upgrade_hardy --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc813 --outputisoname cooperation-iws-opengeu-8.04.1-update-090310.iso --isotype opengeu_8.04.1 --ostype Client --silent

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/Poseidon.3.1_32bits.iso --modulesfile templates/upgrade_hardy --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc816 --outputisoname cooperation-iws-poseidon-update-090310.iso --isotype poseidon-3.1 --ostype Client --silent


./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/ubuntu_8.10_netbook_remix.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc817 --outputisoname cooperation-iws-netbook-remix-8.10-update-090310.iso --isotype netbook-remix_8.10 --ostype Client --silent --ostype Client

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/kubuntu-8.10-desktop-i386.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc818 --outputisoname cooperation-iws-kubuntu-8.10-update-090310.iso --silent --ostype Client

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/ubuntu-8.10-desktop-i386.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/0zc819 --outputisoname cooperation-iws-ubuntu-8.10-update-090310.iso --silent --ostype Client

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/ubuntu_studio_8.10.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --directory /media/partage-dev/tmp/0zc820 --outputisoname cooperation-iws-gw-intranet-0.7.1.iso --isotype studio_8.10 --silent --ostype Client

./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/eeebuntu-2.0-base.iso --modulesfile templates/upgrade_intrepid --webappmirror http://localhost:81/depot --debmirror http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --cms Wordpress --directory /media/partage-dev/tmp/10zc82 --outputisoname cooperation-iws-eeebuntu-nbr-2.0-update-090310.iso --isotype eeebuntu_8.10 --silent --ostype Client

sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/kubuntu-8.04.1-desktop-i386.iso --modulesfile templates/upgrade_hardy http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --directory /media/partage-dev/tmp/6a2 --silent --outputisoname ciws-kubuntu-8.04.1-client-0.5.2.iso --ostype Client

sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/ubuntu-8.04.1-desktop-i386.iso --modulesfile templates/upgrade_hardy -http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --directory /media/partage-dev/tmp/6a3 --silent --outputisoname ciws-ubuntu-8.04.1-client-0.5.2.iso --ostype Client


sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/xubuntu-8.04.1-desktop-i386.iso --modulesfile templates/upgrade_hardy http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --directory /media/partage-dev/tmp/6a4 --silent --outputisoname ciws-xubuntu-8.04.1-client-0.5.2.iso --ostype Client 



sudo ./cooperation-iws.py -c --createdirectories --isofile /media/partage-dev/ISO/Live/xubuntu-8.10-desktop-i386.iso --modulesfile templates/upgrade_intrepid http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --debmirrornonfree http://localhost:3142/packages.medibuntu.org/ --debmirrorsecurity http://localhost:3142/fr.archive.ubuntu.com/ubuntu/ --directory /media/partage-dev/tmp/6a6  --silent --outputisoname ciws-xubuntu-8.10-client-0.5.2.iso --ostype Client



