#!/bin/bash
domain="admin.intra"
generic_admin_email="admin.local@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"
#kernel bigmem lenny upgrade
#update live-initramfs
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="y"
secure_admin="y"
apache_admin_pwd=$generic_login_pwd
mysql_root_password=$generic_mysql_pwd
#Samba
smb_pwd=$generic_login_pwd
#Proftpd
proftpd_pwd=$generic_login_pwd
#Snif
nb_snif=1
snif_name[1]="Snif"
share_snif_smb[1]="y"
share_snif_smb_pwd[1]="n"
#Snort 2.8 Base 1.3.9 server Intrepid
snort_registration_key=""
base_name="Base"
snort_mysql_pwd=$generic_mysql_pwd
snort_listening_interface="eth0"
#SSH Server
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Awstats
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cooperation-iws Liveusb 0.4
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#Cacti 0.8.7b
cacti_name="Cacti"
cacti_mysql_pwd=$generic_mysql_pwd
#Roundcube 0.2
#Horde 1.2
#Postfix, Dovecot, PostfixAdmin, Clamav, Mailscanner Lenny releases
postfixadmin_name="Mail"
postfixadmin_mysql_pwd=$generic_mysql_pwd
public_mail="y"
mail_domain=$domain
mailbox_quota="1000"
admin_email=$generic_admin_email
#Syslog-ng server
syslog_admin_email=$generic_admin_email
phpsyslog_mysql_pwd=$generic_mysql_pwd
phpsyslogng_name="Phpsyslogng"
#Zabbix 1.6
zabbix_name="zabbix"
zabbix_mysql_pwd=$generic_mysql_pwd
#DNS server lenny
