#!/bin/bash
domain="data.intra"
generic_admin_email="admin.local@admin.intra"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"
#DNS server lenny
#kernel bigmem lenny upgrade
kernel="2.6.26-1-686-bigmem"
#update live-initramfs
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="y"
secure_admin="y"
apache_admin_pwd=$generic_login_pwd
mysql_root_password=$generic_mysql_pwd
#Samba
smb_pwd=$generic_login_pwd
#Proftpd
proftpd_pwd=$generic_login_pwd
#KnowledgeTree 3.5.2c
nb_kt=1
kt_name[1]="Knowledgetree"
kt_mysql_pwd[1]=$generic_mysql_pwd
kt_admin_email[1]=$generic_admin_email
#Nuxeo 5.1.5GA
nuxeo_name="Nuxeo"
nuxeo_install_ooo="y"
nuxeo_mysql_pwd=$generic_mysql_pwd
nuxeo_admin_email=$generic_admin_email
#SSH Server
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Awstats
#Cacti 0.8.7b
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cooperation-iws Liveusb 0.4
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#Postfix Relay Client
smtp_postfix_client_relay="administration.admin.intra"
#Zabbix client 1.6
zabbix_server_name="administration.admin.intra"
#Syslog client lenny
syslog_server_name="administration.admin.intra"
#Snort2.8 client Intrepid
snort_remote_name="Base"
snort_registration_key=""
snort_server_mysql_pwd=$generic_mysql_pwd
snort_server_name="administration.admin.intra"
snort_listening_interface="eth0"
