#!/bin/bash
domain="cooperation-iws.intra"
generic_admin_email="admin.local@admin.intra"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="Lokkir10"
apache_user="www-data"
#SSH Server
#update live-initramfs
#kernel bigmem lenny upgrade
kernel="2.6.26-1-686-bigmem"
#ssl
#Flashplayer Lenny
#Madwifi Lenny

###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="y"
secure_admin="y"
apache_admin_pwd=$generic_login_pwd
mysql_root_password=$generic_mysql_pwd
#Gateway DNS 0.4
gateway_nb_machine=10
gateway_net_iface="eth0"
gateway_local_iface="eth1"
domain="cooperation-iws.intra"
#Ntop
#Awstats
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Snort2.8 Base1.3.9 standalone Intrepid
snort_registration_key=""
base_name="Base"
snort_mysql_pwd=$generic_mysql_pwd
snort_listening_interface="eth0"
#debian netbook
#Postfix Relay Client
smtp_postfix_client_relay="administration.admin.intra"

