#!/bin/bash
domain="gforge.intra"
generic_admin_email="admin.local@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"
#DNS server lenny
#kernel bigmem lenny upgrade
#update live-initramfs

#Gforge Lenny
smtp_postfix_client_relay="ciwsvn.cooperation-iws.intra"
gforge_admin_email="admin.dev@cooperation-iws.intra"

