#!/bin/bash

#kernel bigmem lenny upgrade
kernel="2.6.26-1-686-bigmem"
#update live-initramfs
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
#Kolab 2.2
kolab_domain_name="kolab"
kolab_domain_ext="intra"
domain="$kolab_domain_name.$kolab_domain_ext"
kolab_admin_mail="admin.kolab"
kolab_pwd=$generic_login_pwd
apache_user="kolab"
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#SSH Server
#Ossec 1.5.1 standalone
ossec_report_address="$kolab_admin_mail@$domain"
#Cooperation-iws Liveusb 0.4
#Zabbix client 1.6
zabbix_server_name="administration.admin.intra"
#Syslog client lenny
syslog_server_name="administration.admin.intra"
##Snort2.8 client Intrepid
snort_remote_name="Base"
snort_registration_key=""
snort_server_mysql_pwd=$generic_mysql_pwd
snort_server_name="administration.admin.intra"
snort_listening_interface="eth0"
#DNS server lenny
#Flashplayer Lenny
#Madwifi Lenny

