#!/bin/bash

#Ubuntu Multimedia Codecs
#Multimedia Client
#Cooperation-iws Liveusb 0.4
#kernel upgrade
#Qtpart2ed
#Ntfs-config
#Office client
#Wine windows emulator

#eeebox hack
#NX Client
#install live-initramfs Hardy
