#!/bin/bash

#Ubuntu Multimedia Codecs
#Multimedia Client
#Cooperation-iws Liveusb 0.4
#Virtualbox-ose
#Auto upgrade
#kernel upgrade
#SSH Server
#Qtparted
#Ntfs-config
#Office client
#Wine windows emulator
#languages support
#Remastersys fix
