#!/bin/bash

###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="n"
secure_admin="n"
apache_admin_pwd=""
#Samba
smb_pwd="cooperation"
#Proftpd
proftpd_pwd="cooperation"
#KnowledgeTree 3.5.2c
#Nuxeo 5.1.5GA
nuxeo_install_ooo="y"
#Snif
share_snif_smb1="y"
share_snif_smb_pwd1="n"
#SSH Server
#Jdicd 1.5
#Net2ftp 0.97
#Ossec 1.5.1 standalone
ossec_report_address="admin@ciws.com"
#Awstats
#Cacti 0.8.7b
#Akoie 0.5
share_akoie_smb="y"
share_akoie_smb_pwd="n"
#Clamav antivirus
clam_mail_report="admin@ciws.com"
#Cooperation-iws Liveusb 0.3
#Webmin 1.4.20
webmin_pwd="cooperation"
#Postfix Relay Client
smtp_postfix_client_relay="mail.ciws.com"
#Zabbix client 1.6
zabbix_server_name="administration.ciws.com"
#Syslog client
syslog_server_name="administration.ciws.com"
#Snort2.8 client
snort_registration_key=""
snort_server_mysql_pwd="SNORT_MYSQL_PWD"
snort_server_name="administration.ciws.com"
