#!/bin/bash
generic_admin_email="admin@ciws.com"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"

###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="n"
secure_admin="n"
apache_admin_pwd=""
#Samba
smb_pwd=$generic_login_pwd
#Proftpd
proftpd_pwd=$generic_login_pwd
#KnowledgeTree 3.5.2c
nb_kt=1
kt_name[1]="Knowledgetree"
kt_mysql_pwd[1]=$generic_mysql_pwd
kt_admin_email[1]=$generic_mysql_pwd
#Nuxeo 5.1.5GA
nuxeo_name="Nuxeo"
nuxeo_install_ooo="y"
nuxeo_mysql_pwd=$generic_mysql_pwd
nuxeo_admin_email=$generic_admin_email
#SSH Server
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Awstats
#Cacti 0.8.7b
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cooperation-iws Liveusb 0.3
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#Postfix Relay Client
smtp_postfix_client_relay="mail.ciws.com"
#Zabbix client 1.6
zabbix_server_name="administration.ciws.com"
#Syslog client
syslog_server_name="administration.ciws.com"
#Snort2.8 client
snort_registration_key=""
snort_server_mysql_pwd=$generic_mysql_pwd
snort_server_name="administration.ciws.com"
