#!/bin/bash
domain="cooperation-iws.intra"
generic_admin_email="admin.local@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"
#kernel bigmem lenny upgrade
kernel="2.6.26-1-686-bigmem"
#update live-initramfs

