#!/bin/bash
domain="cooperation-iws.intra"
generic_admin_email="admin.local@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"
#kernel bigmem lenny upgrade
#update live-initramfs
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="y"
secure_admin="y"
apache_admin_pwd=$generic_login_pwd
mysql_root_password=$generic_mysql_pwd
#Awstats
#Wordpress2.6.3
nb_wordpress=1
wordpress_mysql_pwd[1]=$generic_mysql_pwd
wordpress_name[1]="Wordpress"
wordpress_admin_email[1]=$generic_admin_email
#Piwigo 2.0.0
nb_piwigo=1
piwigo_mysql_pwd[1]=$generic_mysql_pwd
piwigo_name[1]="Piwigo"
piwigo_admin_email[1]=$generic_admin_email
#Lilina 1.0
nb_lilina=1
lilina_name[1]="Lilina"
#Laconica 1.8
nb_laconica=1
laconica_mysql_pwd[1]=$generic_mysql_pwd
laconica_name[1]="Laconica"
laconica_admin_email[1]=$generic_admin_email
#Scenari


