#!/bin/bash
domain="cooperation-iws.intra"
generic_admin_email="admin.local@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"
#Auto upgrade
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="n"
secure_admin="n"
apache_admin_pwd=$generic_login_pwd
#Samba
smb_pwd=$generic_login_pwd
#Proftpd
proftpd_pwd=$generic_login_pwd
#Dotproject 2.1.2
nb_dotproject=1
dotproject_mysql_pwd[1]=$generic_mysql_pwd
dotproject_name[1]="Dotproject"
dotproject_admin_pwd[1]=$generic_login_pwd
dotproject_admin_email[1]=$generic_admin_email
#Achievo 1.3.4
nb_achievo=1
achievo_mysql_pwd[1]=$generic_mysql_pwd
achievo_name[1]="Achievo"
achievo_admin_pwd[1]=$generic_login_pwd
#Bugzilla3.0.5b
nb_bugzilla=1
bugzilla_mysql_pwd[1]=$generic_mysql_pwd
bugzilla_name[1]="Bugzilla"
bugzilla_admin_email[1]=$generic_admin_email
bugzilla_admin_name[1]="admin"
bugzilla_admin_pwd[1]=$generic_login_pwd
#Mantis1.1.2
nb_mantis=1
mantis_mysql_pwd[1]=$generic_mysql_pwd
mantis_name[1]="Mantis"
#Trac Subversion 0.11.2
svn_admin_pwd=$generic_login_pwd
svn_anonymous_pwd=""
trac_admin_pwd=$generic_login_pwd
#Taskfreak 0.6.2
nb_taskfreak=1
taskfreak_mysql_pwd[1]=$generic_mysql_pwd
taskfreak_name[1]="Taskfreak"
taskfreak_admin_email[1]=$generic_admin_email
#SSH Server
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Net2ftp 0.97
net2ftp_admin_mail=$generic_admin_email
net2ftp_admin_pwd=$generic_login_pwd
net2ftp_admin_name="admin"
net2ftp_mysql_pwd=$generic_mysql_pwd
net2ftp_name="Net2ftp"
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cooperation-iws Liveusb 0.3
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#Cacti 0.8.7b
cacti_name="Cacti"
cacti_mysql_pwd=$generic_mysql_pwd
#Postfix Relay Client
smtp_postfix_client_relay="mail.$domain"
#Zabbix client 1.6
zabbix_server_name="administration.$domain"
#Syslog client
syslog_server_name="administration.$domain"
#Snort2.8 client Intrepid
snort_remote_name="Base"
snort_registration_key=""
snort_server_mysql_pwd=$generic_mysql_pwd
snort_server_name="administration.$domain"
snort_listening_interface="eth0"
#Awstats
