#!/bin/bash

###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="n"
secure_admin="n"
apache_admin_pwd=""
#Samba
smb_pwd="cooperation"
#Proftpd
proftpd_pwd="cooperation"
#Jdicd 1.5
#Mediawiki 1.12.0
#Wordpress2.5.1
#Achievo 1.3.4
#Bugzilla
bugzilla_admin_email="admin@ciws.com"
bugzilla_admin_name="admin"
bugzilla_admin_pwd="cooperation"
#Mantis1.1.2
#Radria 0.8.4
#Trac Subversion
svn_admin_pwd="cooperation"
svn_anonymous_pwd=""
trac_admin_pwd="cooperation"
#PhpBB 3.0.2
#Taskfreak 1.8
#SSH Server
#OpenGoo 1.0
#Ossec 1.5.1 standalone
#Awstat
#Net2ftp 0.97
#Akoie 0.5
share_akoie_smb="y"
share_akoie_smb_pwd="n"
#Clamav antivirus
clam_mail_report="admin@ciws.com"
#Cooperation-iws Liveusb 0.3
#Webmin 1.4.20
webmin_pwd="cooperation"
#Cacti 0.8.7b
#Postfix Relay Client
smtp_postfix_client_relay="mail.ciws.com"
#Zabbix client 1.6
zabbix_server_name="administration.ciws.com"
#Syslog client
syslog_server_name="administration.ciws.com"
#Snort2.8 client
snort_registration_key=""
snort_server_mysql_pwd="SNORT_MYSQL_PWD"
snort_server_name="administration.ciws.com"
