#!/bin/bash
domain="ciws.com"
generic_admin_email="admin@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"


###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="n"
secure_admin="n"
apache_admin_pwd=$generic_login_pwd
#Samba
smb_pwd=$generic_login_pwd
#Proftpd
proftpd_pwd=$generic_login_pwd
#Roundcube 0.2
#Achievo 1.3.4
nb_achievo=1
achievo_mysql_pwd[1]=$generic_mysql_pwd
achievo_name[1]="Achievo"
achievo_admin_pwd[1]=$generic_login_pwd
#Bugzilla
bugzilla_mysql_pwd=$generic_mysql_pwd
bugzilla_name="Bugzilla"
bugzilla_admin_email=$generic_admin_email
bugzilla_admin_name="admin"
bugzilla_admin_pwd=$generic_login_pwd
#Mantis1.1.2
nb_mantis=1
mantis_mysql_pwd[1]=$generic_mysql_pwd
mantis_name[1]="Mantis"
#Radria 0.8.4
radria_name="Radria"
radria_mysql_pwd=$generic_mysql_pwd
#Trac Subversion
svn_admin_pwd=$generic_login_pwd
svn_anonymous_pwd=""
trac_admin_pwd=$generic_login_pwd
#Taskfreak 1.8
nb_taskfreak=1
taskfreak_mysql_pwd[1]=$generic_mysql_pwd
taskfreak_name[1]="Taskfreak"
taskfreak_admin_email[1]=$generic_admin_email
#SSH Server
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Net2ftp 0.97
net2ftp_admin_mail=$generic_admin_email
net2ftp_admin_pwd=$generic_login_pwd
net2ftp_admin_name="admin"
net2ftp_mysql_pwd=$generic_mysql_pwd
net2ftp_name="Net2ftp"
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cooperation-iws Liveusb 0.3
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#Cacti 0.8.7b
cacti_name="Cacti"
cacti_mysql_pwd=$generic_mysql_pwd
#Snort2.8 Base1.3.9 standalone
snort_registration_key=""
base_name="Base"
snort_mysql_pwd=$generic_mysql_pwd
#Postfix, Dovecot, PostfixAdmin, Clamav, Mailscanner
postfixadmin_name="Mail"
postfixadmin_mysql_pwd=$generic_mysql_pwd
public_mail="n"
mail_domain=$domain
smtp_relay="smtp.free.fr"
mailbox_quota="100"



