#!/bin/bash
domain="cooperation-iws.intra"
generic_admin_email="admin.local@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"

#kernel bigmem lenny upgrade
kernel="2.6.26-1-686-bigmem"
#update live-initramfs
#Flashplayer Lenny
#Madwifi Lenny
#ssl
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="y"
secure_admin="y"
apache_admin_pwd=$generic_login_pwd
mysql_root_password=$generic_mysql_pwd
#Samba
smb_pwd=$generic_login_pwd
#Proftpd
proftpd_pwd=$generic_login_pwd
#Gallery 2.3RC1
nb_gallery=1
gallery_name[1]="Gallery"
gallery_mysql_pwd[1]=$generic_mysql_pwd
gallery_pwd[1]=$generic_login_pwd
gallery_admin_email[1]=$generic_admin_email
#Jdicd 1.5b
#Snif
nb_snif=1
snif_name[1]="Snif"
share_snif_smb[1]="y"
share_snif_smb_pwd[1]="n"
#Wordpress2.6.3
nb_wordpress=1
wordpress_mysql_pwd[1]=$generic_mysql_pwd
wordpress_name[1]="Wordpress"
wordpress_admin_email[1]=$generic_admin_email
#SSH Server
#OpenGoo 1.0
nb_opengoo=1
opengoo_mysql_pwd[1]=$generic_mysql_pwd
opengoo_name[1]="Opengoo"
opengoo_admin_email[1]=$generic_admin_email
##Taskfreak 0.6.2
nb_taskfreak=1
taskfreak_mysql_pwd[1]=$generic_mysql_pwd
taskfreak_name[1]="Taskfreak"
taskfreak_admin_email[1]=$generic_admin_email
#Drupal 6.6
nb_drupal=1
drupal_mysql_pwd[1]=$generic_mysql_pwd
drupal_name[1]="Drupal"
drupal_admin_mail[1]=$generic_admin_email

#Mediawiki 1.13.0
nb_mediawiki=1
mediawiki_mysql_pwd[1]=$generic_mysql_pwd
mediawiki_name[1]="Mediawiki"
mediawiki_site_name[1]="Ciws"
mediawiki_admin_email[1]=$generic_admin_email
#PhpBB 3.0.3
nb_phpbb=1
phpbb_mysql_pwd[1]=$generic_mysql_pwd
phpbb_name[1]="Phpbb"
phpbb_admin_email[1]=$generic_admin_email
#Jdicd 1.5
#eyeOS 1.6.0.3-1
nb_eyeos=1
eyeos_name[1]="Eyeos"
#Net2ftp 0.97
net2ftp_admin_mail=$generic_admin_email
net2ftp_admin_pwd=$generic_login_pwd
net2ftp_admin_name="admin"
net2ftp_mysql_pwd=$generic_mysql_pwd
net2ftp_name="Net2ftp"
#Claroline 1.8
nb_claroline=1
claroline_mysql_pwd[1]=$generic_mysql_pwd
claroline_name[1]="Claroline"
claroline_admin_email[1]=$generic_admin_email
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Lifetype 1.2b
nb_lifetype=1
lifetype_mysql_pwd[1]=$generic_mysql_pwd
lifetype_name[1]="Lifetype"
lifetype_admin_email[1]=$generic_admin_email
#Spip 1.9.2e
nb_spip=1
spip_mysql_pwd[1]=$generic_mysql_pwd
spip_name[1]="Spip"
spip_admin_email[1]=$generic_admin_email
#Cacti 0.8.7b
cacti_name="Cacti"
cacti_mysql_pwd=$generic_mysql_pwd
#Akoie 0.5
share_akoie_smb="y"
share_akoie_smb_pwd="n"
#Openmeetings
openmeeting_name="openmeetings"
openmeeting_mysql_pwd=$generic_mysql_pwd
#Inspircd
#Cgi IRC
url_default_server="localhost"

#Roundcube 0.2
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cooperation-iws Liveusb 0.4
#Awstats
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#Snort2.8 Base1.3.9 standalone Intrepid
snort_registration_key=""
base_name="Base"
snort_mysql_pwd=$generic_mysql_pwd
snort_listening_interface="eth0"
#Postfix, Dovecot, PostfixAdmin, Clamav, Mailscanner Lenny releases
postfixadmin_name="Mail"
postfixadmin_mysql_pwd=$generic_mysql_pwd
public_mail="n"
mail_domain=$domain
smtp_relay="smtp.free.fr"
mailbox_quota="100"
admin_email=$generic_admin_email
#Agora
nb_agora=1
agora_mysql_pwd[1]=$generic_mysql_pwd
agora_name[1]="Agora"
agora_admin_email[1]=$generic_admin_email
#Clickheat 1.8
clickheat_name="Clickheat"
#Dokeos 1.8.5
nb_dokeos=1
dokeos_mysql_pwd[1]=$generic_mysql_pwd
dokeos_name[1]="Dokeos"
dokeos_admin_email[1]=$generic_admin_email
dokeos_videoconf="n"
#Lodel 0.7.5
nb_lodel=1
lodel_mysql_pwd[1]=$generic_mysql_pwd
lodel_name[1]="Lodel"
lodel_admin_email[1]=$generic_admin_email
#PhpmyResa 0.7.5
nb_resa=1
resa_mysql_pwd[1]=$generic_mysql_pwd
resa_name[1]="Resa"
resa_admin_email[1]=$generic_admin_email

