#!/bin/bash

###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="n"
secure_admin="n"
apache_admin_pwd=""


#Samba
smb_pwd="cooperation"

#Proftpd
proftpd_pwd="cooperation"

#Gallery 2.3RC1

#Snif
share_snif_smb1="y"
share_snif_smb_pwd1="n"

#Wordpress2.5.1

#SSH Server

#OpenGoo 0.8

#Moodle 1.9

#Taskfreak 1.8

#Mediawiki 1.12.0

#PhpBB 3.0.2

#Jdicd 1.5

#eyeOS 1.6.0.3-1

#Net2ftp 0.97

#Claroline 1.8

#Ossec 1.5.1

#Lifetype 1.2

#Spip 1.9.2d

#Cacti 0.8.7b

#Akoie 0.5
share_akoie_smb="y"
share_akoie_smb_pwd="n"

#Clamav antivirus
clam_mail_report="admin@ciws.com"

#Cooperation-iws Liveusb 0.3

#Awstat

#Webmin 1.4.20
webmin_pwd="cooperation"
#Zabbix client 1.6
zabbix_server_name="mail.ciws.com"
#Syslog client
syslog_server_name="mail.ciws.com"
#Snort2.8 client
snort_registration_key=""
snort_server_mysql_pwd="SNORT_MYSQL_PWD"
snort_server_name="mail.ciws.com"
