#!/bin/bash

###Cooperation-iws gui
sphider_auto_index="y"


#Samba
smb_pwd="cooperation"

#Proftpd
proftpd_pwd="cooperation"

#Gallery 2.3RC1

#Snif
share_snif_smb1="y"
share_snif_smb_pwd1="n"

#Roundcube 0.2

#Wordpress2.5.1

#SSH Server

#OpenGoo 0.8

#Moodle 1.9

#Taskfreak 1.8

#Mediawiki 1.12.0

#PhpBB 3.0.2

#Jdicd 1.5

#eyeOS 1.6.0.3-1

#Net2ftp 0.97

#Claroline 1.8

#Ossec 1.5.1

#Postfix, Dovecot, PostfixAdmin, Clamav, Mailscanner

#Lifetype 1.2

#Spip 1.9.2d

#Cacti 0.8.7b

#Akoie 0.5
share_akoie_smb="y"
share_akoie_smb_pwd="n"

#Clamav antivirus
clam_mail_report="admin@ciws.com"

#Cooperation-iws Liveusb 0.3

#Webmin 1.4.20
webmin_pwd="cooperation"
