#!/bin/bash

###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="n"
secure_admin="n"
apache_admin_pwd=""
#Samba
smb_pwd="cooperation"
#Proftpd
proftpd_pwd="cooperation"
#Snif
share_snif_smb1="y"
share_snif_smb_pwd1="n"
#Roundcube 0.2
#Horde 1.2
#SSH Server
#OpenGoo 1.0
#Awstats
#Ossec 1.5.1 standalone
ossec_report_address="admin@ciws.com"
#Postfix, Dovecot, PostfixAdmin, Clamav, Mailscanner
postfixadmin_name="Mail"
postfixadmin_mysql_pwd="MAILSERVER_MYSQL_PWD"
public_mail="y"
mail_domain="ciws.com"
smtp_relay="smtp.free.fr"
mailbox_quota="100"
#Clamav antivirus
clam_mail_report="admin@ciws.com"
#Cooperation-iws Liveusb 0.3
#Webmin 1.4.20
webmin_pwd="cooperation"
#Cacti 0.8.7b
cacti_name="Cacti"
cacti_mysql_pwd="CACTI_MYSQL_PWD"
#Zabbix client 1.6
zabbix_server_name="administration.ciws.com"
#Syslog client
syslog_server_name="administration.ciws.com"
#Snort2.8 client
snort_registration_key=""
snort_server_mysql_pwd="SNORT_MYSQL_PWD"
snort_server_name="administration.ciws.com"
