#!/bin/bash

###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="n"
secure_admin="n"
apache_admin_pwd=""


#Samba
smb_pwd="cooperation"

#Proftpd
proftpd_pwd="cooperation"



#Snif
share_snif_smb1="y"
share_snif_smb_pwd1="n"

#Roundcube 0.2

#Horde 1.2


#SSH Server

#OpenGoo 0.8

#Ossec 1.5.1

#Postfix, Dovecot, PostfixAdmin, Clamav, Mailscanner
public_mail="y"
mail_domain="ciws.com"
smtp_relay="smtp.free.fr"

#Clamav antivirus
clam_mail_report="admin@ciws.com"

#Cooperation-iws Liveusb 0.3

#Webmin 1.4.20
webmin_pwd="cooperation"

#Cacti 0.8.7b
