#!/bin/bash
domain="cooperation-iws.intra"
generic_admin_email="admin.local@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"


#Kerrighed v5 lenny
gateway_net_iface="eth0"
gateway_local_iface="eth1"


