#!/bin/bash



#Kolab 2.2
kolab_domain_name="ciws"
kolab_domain_ext="com"
domain="$kolab_domain_name.$kolab_domain_ext"
kolab_admin_mail="admin.local"
kolab_pwd="cooperation"
apache_user="kolab"
#Webmin 1.4.20
webmin_pwd="cooperation"
#SSH Server
#Ossec 1.5.1 standalone
ossec_report_address="$kolab_admin_mail@$domain"
#Cooperation-iws Liveusb 0.3
#Zabbix client 1.6
zabbix_server_name="administration.$domain"
#Syslog client
syslog_server_name="administration.$domain"
#Snort2.8 client
snort_remote_name="Base"
snort_registration_key=""
snort_server_mysql_pwd=$generic_mysql_pwd
snort_server_name="administration.$domain"
snort_listening_interface="eth0"
