#!/bin/bash
domain="cooperation-iws.intra"
generic_admin_email="admin.local@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"
#kernel bigmem lenny upgrade
kernel="2.6.26-1-686-bigmem"
#update live-initramfs
#Flashplayer Lenny
#Madwifi Lenny
#ssl
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="y"
secure_admin="y"
apache_admin_pwd=$generic_login_pwd
mysql_root_password=$generic_mysql_pwd
#Proftpd
proftpd_pwd=$generic_login_pwd
#Roundcube 0.2
#SugarCRM 5.2
nb_sugarcrm=1
sugarcrm_mysql_pwd[1]=$generic_mysql_pwd
sugarcrm_name[1]="SugarCRM"
sugarcrm_admin_email[1]=$generic_admin_email
#Cacti 0.8.7b
cacti_name="Cacti"
cacti_mysql_pwd=$generic_mysql_pwd
#Akoie 0.5
share_akoie_smb="n"
share_akoie_smb_pwd="n"
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cooperation-iws Liveusb 0.4
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#Snort2.8 Base1.3.9 standalone Intrepid
snort_registration_key=""
base_name="Base"
snort_mysql_pwd=$generic_mysql_pwd
snort_listening_interface="eth0"
#Postfix, Dovecot, PostfixAdmin, Clamav, Mailscanner Lenny releases
postfixadmin_name="Mail"
postfixadmin_mysql_pwd=$generic_mysql_pwd
public_mail="n"
mail_domain=$domain
smtp_relay="smtp.free.fr"
mailbox_quota="100"
admin_email=$generic_admin_email
#Dotproject 2.1.2
nb_dotproject=1
dotproject_mysql_pwd[1]=$generic_mysql_pwd
dotproject_name[1]="Dotproject"
dotproject_admin_pwd[1]=$generic_login_pwd
dotproject_admin_email[1]=$generic_admin_email
#Achievo 1.3.4
nb_achievo=1
achievo_mysql_pwd[1]=$generic_mysql_pwd
achievo_name[1]="Achievo"
achievo_admin_pwd[1]=$generic_login_pwd
#Bugzilla3.0.5b
nb_bugzilla=1
bugzilla_mysql_pwd[1]=$generic_mysql_pwd
bugzilla_name[1]="Bugzilla"
bugzilla_admin_email[1]=$generic_admin_email
bugzilla_admin_name[1]="admin"
bugzilla_admin_pwd[1]=$generic_login_pwd
#Redmine 0.8.1
redmine_mysql_pwd=$generic_mysql_pwd
redmine_name="Redmine"
#Lilina 1.0
nb_lilina=1
lilina_name[1]="Lilina"

