#!/bin/bash
domain="perso-sta.intra"
generic_admin_email="admin.local@$domain"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"
#DNS server lenny
#kernel bigmem lenny upgrade
#update live-initramfs
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="y"
secure_admin="y"
apache_admin_pwd=$generic_login_pwd
mysql_root_password=$generic_mysql_pwd
#Proftpd
proftpd_pwd=$generic_login_pwd
#Samba
smb_pwd=$generic_login_pwd
#Gallery 2.3.0
nb_gallery=1
gallery_name[1]="Gallery"
gallery_mysql_pwd[1]=$generic_mysql_pwd
gallery_pwd[1]=$generic_login_pwd
gallery_admin_email[1]=$generic_admin_email
#Piwigo 2.0.0
nb_piwigo=1
piwigo_mysql_pwd[1]=$generic_mysql_pwd
piwigo_name[1]="Piwigo"
piwigo_admin_email[1]=$generic_admin_email
#Lilina 1.0
nb_lilina=1
lilina_name[1]="Lilina"
#Ampache 3.4.3
nb_ampache=1
ampache_mysql_pwd[1]=$generic_mysql_pwd
ampache_name[1]="Ampache"
#eyeOS 1.6.0.3-1
nb_eyeos=1
eyeos_name[1]="Eyeos"
#OpenGoo 1.0
nb_opengoo=1
opengoo_mysql_pwd[1]=$generic_mysql_pwd
opengoo_name[1]="Opengoo"
opengoo_admin_email[1]=$generic_admin_email
##Wordpress2.6.3
nb_wordpress=1
wordpress_mysql_pwd[1]=$generic_mysql_pwd
wordpress_name[1]="Wordpress"
wordpress_admin_email[1]=$generic_admin_email
#Snif
nb_snif=1
snif_name[1]="Snif"
share_snif_smb[1]="y"
share_snif_smb_pwd[1]="n"
#SSH Server
#Jdicd 1.5b
#Mediawiki 1.13.0
nb_mediawiki=1
mediawiki_mysql_pwd[1]=$generic_mysql_pwd
mediawiki_name[1]="Mediawiki"
mediawiki_site_name[1]="Ciws"
mediawiki_admin_email[1]=$generic_admin_email
#Net2ftp 0.97
net2ftp_admin_mail=$generic_admin_email
net2ftp_admin_pwd=$generic_login_pwd
net2ftp_admin_name="admin"
net2ftp_mysql_pwd=$generic_mysql_pwd
net2ftp_name="Net2ftp"
#Dotclear 2.1.3
nb_dotclear=1
dotclear_name[1]="Dotclear"
dotclear_mysql_pwd[1]=$generic_mysql_pwd
dotclear_admin_email[1]=$generic_admin_email
#Taskfreak 0.6.2
nb_taskfreak=1
taskfreak_mysql_pwd[1]=$generic_mysql_pwd
taskfreak_name[1]="Taskfreak"
taskfreak_admin_email[1]=$generic_admin_email
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Awstats
#Roundcube 0.2
#Drupal 6.6
nb_drupal=1
drupal_mysql_pwd[1]=$generic_mysql_pwd
drupal_name[1]="Drupal"
drupal_admin_mail[1]=$generic_admin_email
#Cacti 0.8.7b
cacti_name="Cacti"
cacti_mysql_pwd=$generic_mysql_pwd
#Akoie 0.5
share_akoie_smb="y"
share_akoie_smb_pwd="n"
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cooperation-iws Liveusb 0.4
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#Snort2.8 Base1.3.9 standalone Intrepid
snort_registration_key=""
base_name="Base"
snort_mysql_pwd=$generic_mysql_pwd
snort_listening_interface="eth0"
#Postfix, Dovecot, PostfixAdmin, Clamav, Mailscanner Lenny releases
postfixadmin_name="Mail"
postfixadmin_mysql_pwd=$generic_mysql_pwd
public_mail="n"
mail_domain=$domain
smtp_relay="smtp.free.fr"
mailbox_quota="100"
admin_email=$generic_admin_email
