#!/bin/bash
domain="social.intra"
generic_admin_email="admin.local@admin.intra"
generic_mysql_pwd="mysql_pwd"
generic_login_pwd="cooperation"
apache_user="www-data"
#DNS server lenny
#kernel bigmem lenny upgrade
#update live-initramfs
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="y"
secure_admin="y"
apache_admin_pwd=$generic_login_pwd
mysql_root_password=$generic_mysql_pwd
#Samba
smb_pwd=$generic_mysql_pwd
#Proftpd
proftpd_pwd=$generic_mysql_pwd
#Jdicd 1.5b
#Scuttle
nb_scuttle=1
scuttle_mysql_pwd[1]=$generic_mysql_pwd
scuttle_name[1]="Scuttle"
scuttle_admin_email[1]=$generic_admin_email
#Elgg 1.1
nb_elgg=1
elgg_mysql_pwd[1]=$generic_mysql_pwd
elgg_name[1]="Elgg"
elgg_admin_email[1]=$generic_admin_email

#Mediawiki 1.13.0
nb_mediawiki=1
mediawiki_mysql_pwd[1]=$generic_mysql_pwd
mediawiki_name[1]="Mediawiki"
mediawiki_site_name[1]="Ciws"
mediawiki_admin_email[1]=$generic_admin_email
#Sedna
nb_sedna=1
sedna_mysql_pwd[1]=$generic_mysql_pwd
sedna_name[1]="Sedna"
sedna_admin_email[1]=$generic_admin_email
#Drupal 6.6
nb_drupal=1
drupal_mysql_pwd[1]=$generic_mysql_pwd
drupal_name[1]="Drupal"
drupal_admin_mail[1]=$generic_admin_email
#Wordpress2.6.3
nb_wordpress=1
wordpress_mysql_pwd[1]=$generic_mysql_pwd
wordpress_name[1]="Wordpress"
wordpress_admin_email[1]=$generic_admin_email
#Gallery 2.3.0
nb_gallery=1
gallery_name[1]="Gallery"
gallery_mysql_pwd[1]=$generic_mysql_pwd
gallery_pwd[1]=$generic_login_pwd
gallery_admin_email[1]=$generic_admin_email
#Ampache 3.4.3
nb_ampache=1
ampache_mysql_pwd[1]=$generic_mysql_pwd
ampache_name[1]="Ampache"
#Insoshi
#SSH Server
#OpenGoo 1.0
nb_opengoo=1
opengoo_mysql_pwd[1]=$generic_mysql_pwd
opengoo_name[1]="Opengoo"
opengoo_admin_email[1]=$generic_admin_email
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Net2ftp 0.97
net2ftp_admin_mail=$generic_admin_email
net2ftp_admin_pwd=$generic_login_pwd
net2ftp_admin_name="admin"
net2ftp_mysql_pwd=$generic_mysql_pwd
net2ftp_name="Net2ftp"
#Akoie 0.5
share_akoie_smb="y"
share_akoie_smb_pwd="n"
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cooperation-iws Liveusb 0.4
#Webmin 1.4.20
webmin_pwd=$generic_login_pwd
#Cacti 0.8.7b
cacti_name="Cacti"
cacti_mysql_pwd=$generic_mysql_pwd
#Postfix Relay Client
smtp_postfix_client_relay="administration.admin.intra"
#Zabbix client 1.6
zabbix_server_name="administration.admin.intra"
#Syslog client lenny
syslog_server_name="administration.admin.intra"
#Snort2.8 client Intrepid
snort_remote_name="Base"
snort_registration_key=""
snort_server_mysql_pwd=$generic_mysql_pwd
snort_server_name="administration.admin.intra"
snort_listening_interface="eth0"
#Awstats
#Lilina 1.0
nb_lilina=1
lilina_name[1]="Lilina"
#Laconica 1.8
nb_laconica=1
laconica_mysql_pwd[1]=$generic_mysql_pwd
laconica_name[1]="Laconica"
laconica_admin_email[1]=$generic_admin_email

