#!/bin/bash
domain="cooperation-iws.intra"
generic_admin_email="admin.perso@$domain"
generic_mysql_pwd="dev_pwd"
generic_login_pwd="Lokkir12"
apache_user="www-data"
#SSH Server
#update live-initramfs
#kernel bigmem lenny upgrade
###Cooperation-iws gui
sphider_auto_index="y"
#Lampp conf
secure_mysql="y"
secure_admin="y"
apache_admin_pwd=$generic_login_pwd
mysql_root_password=$generic_mysql_pwd
#Trac Subversion 0.11.2
nb_svn=1
svn_name[1]="project"
svn_admin_pwd[1]=$generic_login_pwd
svn_anonymous_pwd[1]=""
trac_admin_pwd=$generic_login_pwd
#Ossec 1.5.1 standalone
ossec_report_address=$generic_admin_email
#Clamav antivirus
clam_mail_report=$generic_admin_email
#Cacti 0.8.7b
cacti_name="Cacti"
cacti_mysql_pwd=$generic_mysql_pwd
#Snort2.8 Base1.3.9 standalone Intrepid
snort_registration_key=""
base_name="Base"
snort_mysql_pwd=$generic_mysql_pwd
snort_listening_interface="eth0"
#Postfix, Dovecot, PostfixAdmin, Clamav, Mailscanner Lenny releases
postfixadmin_name="Mail"
postfixadmin_mysql_pwd=$generic_mysql_pwd
public_mail="y"
mail_domain=$domain
smtp_relay="smtp.free.fr"
mailbox_quota="1000"
admin_email=$generic_admin_email
#Roundcube 0.2
#DNS server lenny
domain="cooperation-iws.intra"

