#!/bin/bash

#Ubuntu Multimedia Codecs
#Multimedia Client
#Cooperation-iws Liveusb 0.4
#Virtualbox-ose
#SSH Server
#Ntfs-config
#Office client
#Wine windows emulator
#Remastersys fix
#Ubuntu Multimedia Codecs
#Multimedia Client
#Cooperation-iws Liveusb 0.4
#install live-initramfs Intrepid
kernel="2.6.27-11-generic"
#Tor Privoxy Intrepid
#Havp
havp_privoxy_forward="n"
#Truecrypt client
#Clamtk client
#mixxx
#sound-juicer
#Gimp client
#inkscape client
#latex client
#Le Littre
