#!/bin/bash

#install live-initramfs Jaunty
kernel="2.6.28-11-generic"
#Tor Privoxy Jaunty
fixed_ip="y"
proxy_ip="127.0.0.1"
#Havp
havp_privoxy_forward="n"
#Truecrypt client
#Clamtk client
#Ubuntu Multimedia Codecs
#Multimedia Jaunty Client
#SSH Server
#Qtparted
#Ntfs-config
#Office Jaunty client
#Wine windows emulator
#languages support
#Remastersys fix
#Gimp client
#inkscape client
#latex client
#Le Littre
#secure-delete client
#ie6_EN
#Virtualbox-ose
