#!/bin/bash

#Ubuntu Multimedia Codecs
#Multimedia Client
#Cooperation-iws Liveusb 0.4
#Virtualbox-ose
#SSH Server
#Qtparted
#Ntfs-config
#Office client
#Wine windows emulator
#languages support
#Remastersys fix
#Ubuntu Multimedia Codecs
#Multimedia Client
#Cooperation-iws Liveusb 0.4
#install live-initramfs Hardy
kernel="2.6.24-23-generic"
#Tor Privoxy Intrepid
#Havp
havp_privoxy_forward="n"
#Truecrypt client
#Clamtk client
#Gimp client
#inkscape client
#latex client
#Le Littre
